### ISSUE TITLE
Support content-encryption

### ISSUE THREAD

**Issue by ribase** [drone-plugins/drone-s3-sync#13]
Is it possible to set a "content-encryption" like "gzip" in s3_sync?

**Comment by ribase** [comment]
Content-Encoding: gzip, in S3 it sets: x-amz-meta-content-encoding: gzip instead. Chrome still unpacks and renders the file, but FF and Safari display garbled text.

**Comment by ericanderson** [comment]
I would be happy to help but I don't understand the request?

**Comment by rainer-friederich** [comment]
S3 and the go s3 sdk support the setting of the content-encoding header. 
If you upload a gziped file to s3 you have to set 'Content-Encoding' = 'gzip' to be able to parse it in the browser. css or js for an example.

If you set the content-encoding header right now in metadata the s3 sdk sets the header to : x-amz-meta-content-encoding: gzip instead

So we have to set it explicitly in the Api

Heres the Api doc : http://docs.aws.amazon.com/sdk-for-go/api/service/s3/S3.html#PutObject-instance_method

**Comment by divercraig** [comment]
This issue should be resolved by pull request #20

**Comment by tboerger** [comment]
#20 have been merged, so I think we can close this.
