### ISSUE TITLE
docs mention exclude and include but these functions are not implemented

### ISSUE THREAD

**Issue by rainer-friederich** [drone-plugins/drone-s3-sync#15]
The docs [here](http://addons.drone.io/s3_sync/) mention the exclude and include parameter but these  parameters are not implemented. 

Either implement them or remove them from the docs.
The [Rsync Plugin](https://github.com/drone-plugins/drone-rsync/blob/master/main.go) has them implemented for example

**Comment by tboerger** [comment]
The docs are not updated, look at https://github.com/drone-plugins/drone-s3-sync/blob/master/DOCS.md
With the next run they will be updated.

**Comment by tboerger** [comment]
Damn, and please use http://readme.drone.io/plugins/ as http://addons.drone.io/ needs some rework :(
