### ISSUE TITLE
Metadata: x-amz-meta-cache-control is set instead Cache-Control

### ISSUE THREAD

**Issue by kfigiela** [drone-plugins/drone-s3-sync#18]
Looks like a bug. The `x-amz-meta-cache-control` metadata key is set instead of `Cache-Control`. 

`.drone.yml`:

```
...
  s3_sync:
    acl: public-read
    region: $$AWS_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: build/
    target: /
    delete: true
    metadata:
      "*.js":
        Cache-Control: "public, max-age: 10000000"
      "*.css":
        Cache-Control: "public, max-age: 10000000"
      "*.jpg":
        Cache-Control: "public, max-age: 10000000"
      "*.gif":
        Cache-Control: "public, max-age: 10000000"
      "*.png":
        Cache-Control: "public, max-age: 10000000"
      "*.html":
        Cache-Control: "public, max-age: 600"
```

**Comment by ribase** [comment]
Hi @kfigiela 
As you can see in the documentation there is an other option to set "Cache-Control" as metadata.
"http://docs.aws.amazon.com/sdk-for-go/api/service/s3.html#type-PutObjectInput"

If you set via "metadata" you will get "x-amz-meta-cache-control", so it have to be set directly via "Cache-Control".

So its not a bug, its just not implemented.

More or less like this (Sorry markdown dont let me format this 👎 ):
`var cacheControl string`
    `if a.vargs.CacheControl.IsString() {`
        `cacheControl = a.vargs.CacheControl.String()`
    `} else if !a.vargs.CacheControl.IsEmpty() {`
        `contentMap := a.vargs.CacheControl.Map()`
        `for patternExt := range contentMap {`
            `if patternExt == fileExt {`
                `cacheControl = contentMap[patternExt]`
                `break`
            `}`
        `}`
    `}`

`_, err = a.client.CopyObject(&s3.CopyObjectInput{`
                      `Bucket:      aws.String(a.vargs.Bucket),`
            `Key:         aws.String(remote),`
            `CopySource: aws.String(fmt.Sprintf("%s/%s", a.vargs.Bucket, remote)),`
            `ContentType: aws.String(contentType),`
            `ContentEncoding: aws.String(contentEncoding),`
            `CacheControl: aws.String(cacheControl),`
            `ACL:         aws.String(access),`
            `Metadata:          metadata,`
            `MetadataDirective: aws.String("REPLACE"),`
        `})`
