### ISSUE TITLE
501 during upload

### ISSUE THREAD

**Issue by gabro** [drone-plugins/drone-s3-sync#32]
I get

> NotImplemented: A header you provided implies functionality that is not implemented - ERROR 501

whenever I try to upload something. Apparently this is a known issue affecting SDK versions 1.6.2 and earlier.

See: https://github.com/aws/aws-sdk-go/issues/1379

**Comment by tboerger** [comment]
Looks like the sdk needs to be updated. Maybe you can provide a pr?

**Comment by gabro** [comment]
I can try, not super familiar with go though, how are versions managed? Is there a third party tool I need to use?

**Comment by tboerger** [comment]
Please give it a try, the image have been undated with the latest sdk.

**Comment by gabro** [comment]
It works! Thank you for the quick fix @tboerger :)

**Comment by tboerger** [comment]
Great!
