### ISSUE TITLE
Fail to upload

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-s3-sync#4]
I wanted to document this issue even though I haven't had time to dig into the root cause. I was attempting to publish using the `native` branch and run into the following error. http://beta.drone.io/drone/blog/1

```
Uploading "/drone/src/github.com/drone/blog/public/post/drone-named-rookie-of-the-year/index.html" with Content-Type "text/html; charset=utf-8" and permissions "public-read"
ERROR: failed to upload /drone/src/github.com/drone/blog/public/post/drone-discussion-site/index.html to post/drone-discussion-site/index.html: : 
    status code: 404, request id: 
[info] build failed (exit code 1)
```

I switched to the `master` branch version and the sync executed without error. I'm guessing there is a minor step we're missing in the upload process, but not sure. I'll post back a root cause once I've had the chance to research.

**Comment by nlf** [comment]
this should be fixed now, try switching back to the native plugin and reopen if you still have issues.
