### ISSUE TITLE
acl configuration in yaml does not work

### ISSUE THREAD

**Issue by btkostner** [drone-plugins/drone-s3-sync#51]
Using Drone image: `drone/drone:1.0.0-rc.3`

When configuring acl values like so, it does not work:
```
settings:
  acl:
    "*": public-read
```

Bug when configuring it as a JSON string, it seems to work:
```
settings:
  acl: '{ "*": "public-read" }'
```

This might be more of an issue with drone and it's yaml to env parsing. Let me know if you want me to open it up in a different repo instead.

**Comment by tboerger** [comment]
This is an upstream drone issue, nothing we can fix on the plugin. Please report it to the drone repo.
