### ISSUE TITLE
Would the transfer result only successful or failed?

### ISSUE THREAD

**Issue by hellovigoss** [drone-plugins/drone-s3-sync#60]
If there be an error or exception throw out to interrupt drone stage when anything unexpected happen during data transfer？  
eg. some files transfer successful but left failed.

**Comment by hellovigoss** [comment]
I just want to confirm the sync operation is atomic.
And if drone break when failed?

**Comment by tboerger** [comment]
The sync operation is not atomic, I guess the S3 lib is not able to do that.
