### ISSUE TITLE
strange endpoint addition

### ISSUE THREAD

**Issue by vtolstov** [drone-plugins/drone-s3-sync#62]
i have aws s3 compatible endpoint, provide creadentials and set endpoint in step to my host: 
https://s3.selcdn.ru
but drone after try to execute step says:
```
RequestError: send request failed
--
2 | caused by: Get https://www.s3.selcdn.ru/?prefix=: x509: certificate is valid for *.selcdn.ru, selcdn.ru, not www.s3.selcdn.ru
```

i'm recheck and i don't add www prefix to host. why it added?

**Comment by vtolstov** [comment]
my bucket have name www

**Comment by vtolstov** [comment]
problem because path_style plugin settings not documented now and by default false.

**Comment by vtolstov** [comment]
with setting path_style: true all works fine

**Comment by tboerger** [comment]
Feel free to raise a pull request on the plugin index to document the path style.
